### ISSUE TITLE
Undefined symbol: _HEAP

### ISSUE THREAD

**Issue by MeteorShowerSeason** [fluttify-project/core_location_fluttify#1]
Ld /Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Products/Debug-iphoneos/core_location_fluttify/core_location_fluttify.framework/core_location_fluttify normal arm64 (in target 'core_location_fluttify' from project 'Pods')
    cd /Users/meteorshower/Documents/mealfee/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios8.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -L/Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Products/Debug-iphoneos/core_location_fluttify -F/Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Products/Debug-iphoneos/core_location_fluttify -F/Users/meteorshower/Documents/mealfee/ios/Pods/../Flutter -filelist /Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/core_location_fluttify.build/Objects-normal/arm64/core_location_fluttify.LinkFileList -install_name @rpath/core_location_fluttify.framework/core_location_fluttify -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/core_location_fluttify.build/Objects-normal/arm64/core_location_fluttify_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -framework CoreLocation -framework Flutter -framework CoreLocation -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/core_location_fluttify.build/Objects-normal/arm64/core_location_fluttify_dependency_info.dat -o /Users/meteorshower/Library/Developer/Xcode/DerivedData/Runner-elwdreqpbcxsyvevjghidubxwpmv/Build/Products/Debug-iphoneos/core_location_fluttify/core_location_fluttify.framework/core_location_fluttify

Undefined symbols for architecture arm64:
  "_HEAP", referenced from:
      _CLFloorHandler in CLFloorHandler.o
      _CLHeadingHandler in CLHeadingHandler.o
      _CLLocationCoordinate2DHandler in CLLocationCoordinate2DHandler.o
      _CLLocationHandler in CLLocationHandler.o
      _CLLocationManagerHandler in CLLocationManagerHandler.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

When I use it in the latest version of flutter sdk, I have encountered this problem on the ios side, and I have not been able to find a solution. Flutter 1.12.3, xocde 11.4, swift 5.

**Comment by 530209190** [comment]
解决了吗？同求
